export const LOAD_PHONES_SUCCESS = 'LOAD_PHONES_SUCCESS';
export const LOAD_PHONE_SUCCESS = 'LOAD_PHONE_SUCCESS';
export const SET_PHONE_LOADING = 'SET_PHONE_LOADING';
export const SELECT_PHONE_SUCCESS = 'SELECT_PHONE_SUCCESS';
